<?php
/*
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GNU General Public License)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/gpl-license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@refersion.com so we can send you a copy immediately.
 *
 * @category   IMSC
 * @package    IMSC_Refersion
 * @copyright  Copyright (c) 2015 Refersion, Inc.
 * @license    http://opensource.org/licenses/gpl-license GNU General Public License
 */
?>
<?php if($this->isEnabled()):?>
<script type="text/javascript">
var image = new Image(); document.body.appendChild(image); image.src = "<?php echo $this->getSuccessPixel(); ?>"; image.setAttribute('style', 'float: right;width:1px;height:1px;');
</script>
<?php endif; ?>